name: tailscale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Tailscale Action
        uses: ./
        with:
          client_id: ${{ secrets.OAUTH_CLIENT_ID }}
          client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          device_tag: ${{ secrets.DEVICE_TAG }}

      - name: check for hello.ipn.dev in netmap
        run:
          tailscale status | grep -q ^100
